version: '3'
services:
  django:
    container_name: URLShortener_container
    build: .
    restart: always
    command: /bin/bash /dockerize_conf/django_entry_point.sh
    ports:
      - "8000:8000"
    volumes:
      - ./static:/static
      - /docker_URLSH/url_shortener/logs/uwsgi:/logs/uwsgi
      - /docker_URLSH/url_shortener/logs/django:/logs/django
      - uwsgi_socket:/socket
    depends_on:
      - db

  db:
    container_name: pg_container
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/


  nginx:
    container_name: nginx_container
    build: dockerize_conf/nginx
    restart: always
    ports:
      - "80:8080"

    volumes:
      - uwsgi_socket:/socket
      - /docker_URLSH/url_shortener/logs/nginx:/var/log/nginx
      - ./static:/docker_URLSH/static
    depends_on:
      - django

  redis:
    image: redis
    hostname: redis


  # RabbitMQ - queue
  rabbit:
    hostname: rabbit
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=url_shortener
      - RABBITMQ_DEFAULT_PASS=url_shortener
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  keys_root:
  pgdata:
  static:
  media:
  uwsgi_socket:
