swagger: "2.0"
info:
  description: "API document for URL shortener service."
  version: "1.0.0"
  title: "URL Shortener"
  contact:
    email: "MortazMehdi@gmail.com"
host: "localhost:80"
basePath: "/api/v1"
tags:
- name: "shortener"
  description: "Shortener url API"

schemes:
- "https"
- "http"
paths:
  /url_shortener/:
    post:
      summary: "Submit new short URL"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "New URl to submit"
        required: true
        schema:
          $ref: "#/definitions/ShortURL"
      responses:
        "201":
          description: "created"
        "400":
          description: "bad request"
    get:
      summary: "Retreive all URL obj using pagination"
      responses:
        "200":
          description: "ok"
  /url_shortener/{UrlID}/:
    put:
      summary: "Update an existing short url"
      description: "Fully update object"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "UrlID"
        in: "path"
        description: "ID of URL to fully update"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Short url needs to send original_url field"
        required: true
        schema:
          $ref: "#/definitions/ShortURL"
      responses:
        "400":
          description: "Invalid body supplied"
        "404":
          description: "URL obj not found"

    patch:
      summary: "Update an existing short url"
      description: "Fully update object"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "UrlID"
        in: "path"
        description: "ID of URL to partial update"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Short url needs to send original_url field"
        required: true
        schema:
          $ref: "#/definitions/ShortURL"
      responses:
        "400":
          description: "Invalid body supplied"
        "404":
          description: "URL obj not found"
    delete:
      summary: "delete an existing short url"
      parameters:
      - name: "UrlID"
        in: "path"
        description: "ID of URL to delete"
        required: true
        type: "integer"
        format: "int64"

      responses:
        "204":
          description: "no content"
        "404":
          description: "URL obj not found"

  /r/{ShortURL}:
    get:
      summary: "Redirect to original url"
      parameters:
      - name: "ShortURL"
        in: "path"
        description: "Short url"
        required: true
        type: "string"
        format: "string"
      responses:
        "301":
          description: "redirect successfully"
        "404":
          description: "short url not exists!"
        "500":
          description: "internal server error"

definitions:
  ShortURL:
    type: "object"
    properties:
      original_url:
        type: "string"
        format: "url"
      short_url:
        type: "string"
        description: "shorted url | optional"