# Generated by Django 3.2 on 2021-04-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(db_index=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
